export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/login/index',
    'pages/register/index',
    'pages/student/dashboard',
    'pages/student/grades',
    'pages/student/upload',
    'pages/student/analysis',
    'pages/student/ranking',
    'pages/student/trends',
    'pages/student/distribution',
    'pages/student/comparison',
    'pages/student/prediction',
    'pages/student/papers',
    'pages/teacher/dashboard',
    'pages/teacher/grades',
    'pages/teacher/upload',
    'pages/teacher/analysis',
    'pages/teacher/ranking',
    'pages/teacher/trends',
    'pages/teacher/distribution',
    'pages/teacher/comparison',
    'pages/teacher/prediction',
    'pages/profile/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#5b21b6',
    navigationBarTitleText: '成绩分析',
    navigationBarTextStyle: 'white',
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#5b21b6',
    backgroundColor: '#ffffff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/student/dashboard',
        text: '首页',
        iconPath: 'assets/tab-home.png',
        selectedIconPath: 'assets/tab-home-active.png',
      },
      {
        pagePath: 'pages/student/grades',
        text: '成绩',
        iconPath: 'assets/tab-grade.png',
        selectedIconPath: 'assets/tab-grade-active.png',
      },
      {
        pagePath: 'pages/student/upload',
        text: '上传',
        iconPath: 'assets/tab-upload.png',
        selectedIconPath: 'assets/tab-upload-active.png',
      },
      {
        pagePath: 'pages/student/analysis',
        text: '分析',
        iconPath: 'assets/tab-analysis.png',
        selectedIconPath: 'assets/tab-analysis-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tab-profile.png',
        selectedIconPath: 'assets/tab-profile-active.png',
      },
    ],
  },
});
